---
title: "Final Projects"
format: html
editor: visual
---

### Overview

It is time for our final projects! Final projects are worth 24 points (rubric below). The presentations will be on Thursday November 21st and and Tuesday November 26th. There will be 4-5 people in each group, every group will have a github repository for the project with all data/code.

### Rubric

#### 1. Documentation

Github repository (6 points)

-   Nice readme file with CUH logo, description of the project, data, code, and links to each project members github profile

-   Students need to be able to fork the repository and rerun the entire analysis without editing any code

-   Each group member must be marked as a *contributor* on github

#### 2. Code

Exploratory Data Viz (4 points)

-   Visualize the data, highlight key findings

Bayesian Methods (6 points)

-   Utilize a Bayesian approach specific to your project

    -   More details to follow

#### Presentation

Group Presentation (8 points)

-   Show the code as rendered qmd or shiny app (no powerpoints)

    -   Exploratory Data Viz

    -   Bayesian Methods

    -   Results

#### Renewable Energy Forecasting in Spain

[Data on Kaggle](https://www.kaggle.com/datasets/nicholasjhana/energy-consumption-generation-prices-and-weather/data)

Objective: Plot the distribution of total energy demand. Can any of the features in the data help us predict demand? Can any of the features in the data help us predict wind or solar energy generation. Can we forecast a renewable energy sources supply and total energy demand to see the gap?

Guidance: Join the data, extract features from date (day of week, season, hour, etc..), filter city for Barcelona

Group:

-   Wilneris Colon

-   William Kim

-   Eugene Garvilles

-   Andrew Nishitomi
